workflows:
  react_native_expo_ios:
    name: React Native Expo iOS Workflow
    environment:
      xcode: latest
      node: 18
      vars:
        EXPO_TOKEN: Encrypted("${{ secrets.ExpoTokenGroup.EXPO_TOKEN }}")
    scripts:
      - name: Set up dependencies
        script: |
          npm install -g expo-cli
          npm install
      - name: Prebuild the app
        script: |
          expo prebuild --platform ios
      - name: Build iOS app
        script: |
          npx eas-cli build --platform ios --non-interactive --profile production
    artifacts:
      - build/ios/*.ipa
