export { default as TermsSectionOneText } from "./TermsSectionOneText";
export { default as TermsSectionTwoText } from "./TermsSectionTwoText";
export { default as TermsSectionThreeText } from "./TermsSectionThreeText";
export { default as TermsSectionFourText } from "./TermsSectionFourText";
export { default as TermsSectionFiveText } from "./TermsSectionFiveText";
export { default as TermsSectionSixText } from "./TermsSectionSixText";
export { default as TermsSectionSevenText } from "./TermsSectionSevenText";
export { default as TermsSectionEghitText } from "./TermsSectionEghitText";
export { default as TermsSectionNineText } from "./TermsSectionNineText";
